### ISSUE TITLE
Can't work on windows

### ISSUE THREAD

**Issue by XIEBBS** [awaragi/prometheus-mssql-exporter#13]
I got the exceptions on windows：Failed to connect to database: Failed to connect to 192.168.0.97:1443 - connect ECONNREFUSED 192.168.0.97:1443

I am sure I had change server/port/user/passord correctly.
Anybody can help me ?

**Comment by alexandrul** [comment]
The default port is 1433, are you sure your instance is using 1443?
You can check this in the SQL Server Network Configuration / Protocols.

**Comment by awaragi** [comment]
If you are using a named instance, the exporter will not work. Please ensure to enable TCPIP port 1443 for connectivity.
