### ISSUE TITLE
Memory used percentage doesn't match with mssql_total_physical_memory_kb and mssql_available_physical_memory_kb

### ISSUE THREAD

**Issue by babunatarajan** [awaragi/prometheus-mssql-exporter#16]
I see 95 percentage in mssql_memory_utilization_percentage but doesn't correlate with   mssql_total_physical_memory_kb and mssql_available_physical_memory_kb information, I've enough memory available but still the utilization percentage shows more than 90%.

Grafana v7.1.1
Prometheus build date: 20200722-18:51:4 
Grafana Dashboard : https://grafana.com/grafana/dashboards/9336

**Comment by cobolbaby** [comment]
What does `mssql_memory_utilization_percentage` mean?

**Comment by awaragi** [comment]
not exactly sure of this metric but it is a value that is exposed directly by sys.dm_os_process_memory. I usually do not expose percentages as they usually calculated but in this case a DBA requested it so I added. I am leaving to support backward compatiblity
