### ISSUE TITLE
mssql 2008 connect failed

### ISSUE THREAD

**Issue by wanglei8155** [awaragi/prometheus-mssql-exporter#19]
docker logs xxx
...
Failed to connect to database: Failed to connect to xxx:1433
....

**Comment by theKorzh** [comment]
Probably your SQL Server is working as named instance. For named instances the TCP port is dynamically configured by default, so you may need do explicitly specify port in MSSQL settings as described [here](https://docs.microsoft.com/en-US/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver15).

**Comment by awaragi** [comment]
I have added @theKorzh  comments to FAQ section. Part of the 1.1 release. Thanks.

**Comment by astingengo007** [comment]
How can I use named instance to connect like: 1.2.3.4\SKDEV1.5 and custom port 1388 [or even default one]?

**Comment by awaragi** [comment]
Given the library I use for connectivity to mssql servers, only tcpip connections are possible. There are environment variables that allows you to specify the host name and port to connect to. See the https://github.com/awaragi/prometheus-mssql-exporter#environment-variables section about those environment variables.
