### ISSUE TITLE
Port Mapping

### ISSUE THREAD

**Issue by sudhakarapn** [awaragi/prometheus-mssql-exporter#20]
I am running two instances of the container. 

Container 1 - working fine, listening to port 4000 and receiving metrics from MS SQL Server1
Container 2 - is not working since it is trying to listen to port 4000 though I have mapped to port 4001 by using the following command to listen to MS SQL Server2

docker run -e SERVER=192.168.56.101 -e USERNAME=SA -e PASSWORD=qkD4x3yy -e DEBUG=app -p 4001:4001 --name prometheus-mssql-exporter awaragi/prometheus-mssql-exporter

Please suggest.

**Comment by theKorzh** [comment]
It seems that you need to fix your docker command line to expose _container port_ 4000 as _host port_ 4001. Something like **-p 4001:4000**

**Comment by cobolbaby** [comment]
https://github.com/awaragi/prometheus-mssql-exporter/blob/297e0b7a3bba25a8105a23dae00a9beb5ada4ba3/index.js#L21

**Comment by awaragi** [comment]
Dockerfile does not actually publish the port but only suggests to docker which ports will be available but it is up to the application based on configuration to actually make those ports actually functional and using the -p parameter will do the actual publishing.

As @cobolbaby suggested, you can map any external port to the same internal port such as -p 4001:4000 or -p 4002:4000 etc.
