### ISSUE TITLE
Some metrics should be exported as counter instead of gauge

### ISSUE THREAD

**Issue by autopwn** [awaragi/prometheus-mssql-exporter#22]
Some of the metrics should be exported as counter instead of gauge as they are (except for server restarts) monotonically increasing. This would be more in line with the metric types of Prometheus: https://prometheus.io/docs/concepts/metric_types/

- mssql_user_errors
- mssql_log_growths
- mssql_io_stall 
- mssql_page_fault_count
- mssql_kill_connection_errors

**Comment by cobolbaby** [comment]
Limited by the `prom-client` library, the `Counter` class does not support the set method. 

https://github.com/siimon/prom-client/blob/c7b9a9ddd048f6a1921fa1b33c56a5296713aa2b/index.d.ts#L161-L210

**Comment by awaragi** [comment]
Thanks @cobolbaby for the reply. I had originally wanted to use the counters but in any case, Additionally, the format of a gauge and counter is exactly the same in the final output.
