### ISSUE TITLE
sqlserver 2008 r2 can not connect

### ISSUE THREAD

**Issue by qw4285632q** [awaragi/prometheus-mssql-exporter#23]
use the lastest prometheus-mssql-exporter in docker.can not connect to sqlserver 2008 r2. the dynamic port is closed.i have try more than three machine throw same errors like :Failed to connect to database: Failed to connect to *.*.*.*:1433 in 15000m; but i also try sqlserver 2016 and sqlserver 2019.they are ok!!

**Comment by buddynotshotme** [comment]
when i use the latest version，i get an error.
 mssql_up.set(0);
             ^

TypeError: mssql_up.set is not a function
    at D:\k8s\prometheus-mssql-exporter\src\index.js:133:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by awaragi** [comment]
Version 1.2.1 is out and should have fixed the mssql_up.set(0) issue crashing the server. 

The root cause of the probleme however is that the exporter is unable to connect the database. Can you please let me know what kind of error you are getting if that is the case.
