### ISSUE TITLE
The mssql_database_filesize metrics fails on big databases

### ISSUE THREAD

**Issue by enif77** [awaragi/prometheus-mssql-exporter#25]
If a database is so big, that its (size * 8) more than 32bit int max value, the following exception is thrown by the MSSQL server: "Arithmetic overflow error converting expression to data type int.".

The query:

`SELECT DB_NAME(database_id) AS database_name, Name AS logical_name, type, physical_name, (size * 8) size_kb FROM sys.master_files`

at line 124 of the metrics.js file can  be modified like this:

`SELECT DB_NAME(database_id) AS database_name, Name AS logical_name, type, physical_name, (size * cast(8 as bigint)) size_kb FROM sys.master_files`.

If the bigint value wont do any harm later, this change should save the world... :-)

**Comment by cobolbaby** [comment]
![2021-07-26 13-56-43屏幕截图](https://user-images.githubusercontent.com/11460848/126939918-af321bf4-f9a2-4afe-a8b4-fc9e3ee7167d.png)

**Comment by awaragi** [comment]
Thank you for raising the issue. Although late, I have incorporated the change in the next release.

**Comment by awaragi** [comment]
Please note that release 1.0.x is out and include this request
