### ISSUE TITLE
Consider renaming the`up` metric

### ISSUE THREAD

**Issue by bluecmd** [awaragi/prometheus-mssql-exporter#27]
Hi,

Background:
```
$ curl localhost:4000/metrics
# HELP up UP Status
# TYPE up gauge
up 1
[..]
```

`up` is a auto-generated metric by Prometheus often assumed to be referring to whether the exporter is reachable or not. By including it in the response it causes e.g. the commonly used TargetDown alert to fire which are usually only for exporters themselves - e.g. checking the Prometheus "Targets" page would not list this instance. Indeed, given that the `up` metric does not contain anything to differentiate itself, it is virtually impossible to distinguish between "Is the exporter down, or the whole database?".

Instead, if you look at [other](https://github.com/prometheus/blackbox_exporter#checking-the-results) black-box style exporters you see `probe_success` and similar metrics.

Thanks for your consideration,

**Comment by awaragi** [comment]
Thank you for raising the issue. Although late, I have incorporated the change in the next release.

**Comment by awaragi** [comment]
Please note that release 1.0.x is out and include this request
