### ISSUE TITLE
mssql_batch_requests  --> this value is cumulative

### ISSUE THREAD

**Issue by wuzhihui1123** [awaragi/prometheus-mssql-exporter#3]
you said : mssql_batch_requests , Number of Transact-SQL command batches received per second.
but the value that i get from my server is a big value and  always going to increase

thanks for your code  :)

**Comment by cobolbaby** [comment]
Same as https://github.com/awaragi/prometheus-mssql-exporter/issues/22

**Comment by awaragi** [comment]
As @cobolbaby  indicated, we have to use Gauge type but in reality these metrics are effectively cumulative.
