### ISSUE TITLE
Run custom queries

### ISSUE THREAD

**Issue by franciscoed** [awaragi/prometheus-mssql-exporter#6]
Hi,

Any plans to run custom queries?

BTW, nice exporter. 

Thanks

Francisco

**Comment by llech** [comment]
I've made it with some easy adaptations: https://github.com/llech/prometheus-mssql-exporter/commit/f993cacc45ebc77f8e8787345595f9b17853748d

For my use case, I've had to adapt the connection options. I have non-admin uses, so I need to specify database and disable default metrics.

**Comment by awaragi** [comment]
If the point is to run arbitrary sql queries then I suggest using an sql exporter instead which is made for generic queries instead of server health and metrics exporter like this one.

https://github.com/free/sql_exporter

Note there are others but this one pulled 4M+
