### ISSUE TITLE
Can this work with a named instance?

### ISSUE THREAD

**Issue by tupcakes** [awaragi/prometheus-mssql-exporter#7]
I'm trying to connect this to a SQL instance,  but I can't figure out how to get the exporter to connect in to a SQL server in the format servername\instancename.

**Comment by girstenbrei** [comment]
Not at the moment, but changes required shouldn't be that complicated. In the index.js, the config has to be changed to something like the following:
```
let config = {
    connect: {
        server: process.env["SERVER"],
        userName: process.env["USERNAME"],
        password: process.env["PASSWORD"],
        options: {
            // port: process.env["PORT"] || 1433, // <- changed
            encrypt: true,
            rowCollectionOnRequestCompletion: true,
            instanceName: '<yournamedinstance>'  // <- changed
        }
    },
    port: process.env["EXPOSE"] || 4000
};
```
The port needs to be commented out (as a workaround), it is mutually exclusive with the instanceName ([config](https://tediousjs.github.io/tedious/api-connection.html#function_newConnection)).
Would be cool to be able to specify the environment variable INSTANCE (e.g.)!
